OPENAI_MODELS = [
    {"model_id": "gpt-5.5", "name": "GPT-5.5", "input": 5.00, "output": 30.00},
    {"model_id": "gpt-5.5-pro", "name": "GPT-5.5 Pro", "input": 30.00, "output": 180.00},
    {"model_id": "gpt-5.4", "name": "GPT-5.4", "input": 2.50, "output": 15.00},
    {"model_id": "gpt-5.4-mini", "name": "GPT-5.4 Mini", "input": 0.75, "output": 4.50},
    {"model_id": "gpt-5.4-nano", "name": "GPT-5.4 Nano", "input": 0.20, "output": 1.25},
    {"model_id": "gpt-5.4-pro", "name": "GPT-5.4 Pro", "input": 30.00, "output": 180.00},
    {"model_id": "gpt-5.2", "name": "GPT-5.2", "input": 1.75, "output": 14.00},
    {"model_id": "gpt-5.2-pro", "name": "GPT-5.2 Pro", "input": 21.00, "output": 168.00},
    {"model_id": "gpt-5.1", "name": "GPT-5.1", "input": 1.25, "output": 10.00},
    {"model_id": "gpt-5", "name": "GPT-5", "input": 1.25, "output": 10.00},
    {"model_id": "gpt-5-mini", "name": "GPT-5 Mini", "input": 0.25, "output": 2.00},
    {"model_id": "gpt-5-nano", "name": "GPT-5 Nano", "input": 0.05, "output": 0.40},
    {"model_id": "gpt-5-pro", "name": "GPT-5 Pro", "input": 15.00, "output": 120.00},
    {"model_id": "gpt-4.1", "name": "GPT-4.1", "input": 2.00, "output": 8.00},
    {"model_id": "gpt-4.1-mini", "name": "GPT-4.1 Mini", "input": 0.40, "output": 1.60},
    {"model_id": "gpt-4.1-nano", "name": "GPT-4.1 Nano", "input": 0.10, "output": 0.40},
    {"model_id": "gpt-4o", "name": "GPT-4o", "input": 2.50, "output": 10.00},
    {"model_id": "gpt-4o-mini", "name": "GPT-4o Mini", "input": 0.15, "output": 0.60},
    {"model_id": "o4-mini", "name": "O4 Mini", "input": 1.10, "output": 4.40},
    {"model_id": "o3", "name": "O3", "input": 2.00, "output": 8.00},
    {"model_id": "o3-mini", "name": "O3 Mini", "input": 1.10, "output": 4.40},
    {"model_id": "o3-pro", "name": "O3 Pro", "input": 20.00, "output": 80.00},
    {"model_id": "o1", "name": "O1", "input": 15.00, "output": 60.00},
    {"model_id": "o1-mini", "name": "O1 Mini", "input": 1.10, "output": 4.40},
    {"model_id": "o1-pro", "name": "O1 Pro", "input": 150.00, "output": 600.00},
]

GEMINI_MODELS = [
    {"model_id": "gemini-3.1-pro-preview", "name": "Gemini 3.1 Pro Preview", "input": 2.00, "output": 12.00},
    {"model_id": "gemini-3.1-flash-lite-preview", "name": "Gemini 3.1 Flash Lite Preview", "input": 0.25, "output": 1.50},
    {"model_id": "gemini-3-flash-preview", "name": "Gemini 3 Flash Preview", "input": 0.50, "output": 3.00},
    {"model_id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro", "input": 1.25, "output": 10.00},
    {"model_id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash", "input": 0.30, "output": 2.50},
    {"model_id": "gemini-2.5-flash-lite", "name": "Gemini 2.5 Flash Lite", "input": 0.10, "output": 0.40},
    {"model_id": "gemini-2.5-flash-lite-preview-09-2025", "name": "Gemini 2.5 Flash Lite Preview 09-2025", "input": 0.10, "output": 0.40},
    {"model_id": "gemini-2.0-flash", "name": "Gemini 2.0 Flash", "input": 0.10, "output": 0.40},
    {"model_id": "gemini-2.0-flash-lite", "name": "Gemini 2.0 Flash Lite", "input": 0.075, "output": 0.30},
]

ANTHROPIC_MODELS = [
    {"model_id": "claude-opus-4.7", "name": "Claude Opus 4.7", "input": 5.00, "output": 25.00},
    {"model_id": "claude-opus-4.6", "name": "Claude Opus 4.6", "input": 5.00, "output": 25.00},
    {"model_id": "claude-opus-4.5", "name": "Claude Opus 4.5", "input": 5.00, "output": 25.00},
    {"model_id": "claude-opus-4.1", "name": "Claude Opus 4.1", "input": 15.00, "output": 75.00},
    {"model_id": "claude-opus-4", "name": "Claude Opus 4", "input": 15.00, "output": 75.00},
    {"model_id": "claude-sonnet-4.6", "name": "Claude Sonnet 4.6", "input": 3.00, "output": 15.00},
    {"model_id": "claude-sonnet-4.5", "name": "Claude Sonnet 4.5", "input": 3.00, "output": 15.00},
    {"model_id": "claude-sonnet-4", "name": "Claude Sonnet 4", "input": 3.00, "output": 15.00},
    {"model_id": "claude-sonnet-3.7", "name": "Claude Sonnet 3.7", "input": 3.00, "output": 15.00},
    {"model_id": "claude-haiku-4.5", "name": "Claude Haiku 4.5", "input": 1.00, "output": 5.00},
    {"model_id": "claude-haiku-3.5", "name": "Claude Haiku 3.5", "input": 0.80, "output": 4.00},
    {"model_id": "claude-opus-3", "name": "Claude Opus 3", "input": 15.00, "output": 75.00},
    {"model_id": "claude-haiku-3", "name": "Claude Haiku 3", "input": 0.25, "output": 1.25},
]

PROVIDER_CATALOG = {
    "openai": {
        "id": "openai",
        "name": "OpenAI",
        "models": OPENAI_MODELS,
        "supports_prompt_caching": True,
        "prompt_caching_mode": "automatic+hinted",
    },
    "gemini": {
        "id": "gemini",
        "name": "Google Gemini",
        "models": GEMINI_MODELS,
        "supports_prompt_caching": True,
        "prompt_caching_mode": "implicit",
    },
    "anthropic": {
        "id": "anthropic",
        "name": "Anthropic Claude",
        "models": ANTHROPIC_MODELS,
        "supports_prompt_caching": True,
        "prompt_caching_mode": "explicit",
    },
}
